server:
  port: 80

spring:
  application:
    name: cloud-order-service

#euyeka 配置
eureka:
  client:
    # 表示是否将自己注册为 EurekaService  默认true
    register-with-eureka: true
    # 是否从EurekaService中抓取已有的注册信息。默认为true 单节点无所谓，集群必须设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
