server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://rm-8vbp995x3msdf2p5heo.mysql.zhangbei.rds.aliyuncs.com/shijie_server?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: QX8mAy&X5#aRJ8GQUd^x53UvKSXdOF

    druid:
      filters: stat
      initialSize: 2
      maxActive: 300
      maxWait: 60000
      #每60秒运行一次空闲连接回收器
      timeBetweenEvictionRunsMillis: 60000
      #池中的连接空闲30分钟后被回收,默认值就是30分钟。
      minEvictableIdleTimeMillis: 300000
      #验证连接是否可用，使用的SQL语句
      validationQuery: SELECT 1
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testWhileIdle: true
      #借出连接时不要测试，否则很影响性能
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.yajun.springcloud.entities

  #euyeka 配置
eureka:
  client:
    # 表示是否将自己注册为 EurekaService  默认true
    register-with-eureka: true
    # 是否从EurekaService中抓取已有的注册信息。默认为true 单节点无所谓，集群必须设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: payment8003
    prefer-ip-address: true
    # Eureka 客户端向服务端发送心跳的频率 1s
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒） 超时将自动剔除  2s
    lease-expiration-duration-in-seconds: 2