server:
  port: 7001
eureka:
  instance:
    #服务实例名称
    hostname: eureka7001.com
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，不需要检索服务
    fetch-registry: false
    service-url:
      #设置server 交互的地址查询服务和注册服务都需要依赖这个地址,集群相互注册
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    # 心跳时间 间隔 2s 默认30s
    eviction-interval-timer-in-ms: 2000