server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/shijie_box?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

    druid:
      filters: stat
      initialSize: 2
      maxActive: 300
      maxWait: 60000
      #每60秒运行一次空闲连接回收器
      timeBetweenEvictionRunsMillis: 60000
      #池中的连接空闲30分钟后被回收,默认值就是30分钟。
      minEvictableIdleTimeMillis: 300000
      #验证连接是否可用，使用的SQL语句
      validationQuery: SELECT 1
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testWhileIdle: true
      #借出连接时不要测试，否则很影响性能
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.yajun.springcloud.entities
